-- Master Schema Synchronization Migration

-- Workspaces
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

-- Announcements
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS target_departments VARCHAR[];
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS target_roles VARCHAR[];

-- Tasks
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS position DOUBLE PRECISION DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES users(id);

-- Projects
ALTER TABLE projects ADD COLUMN IF NOT EXISTS status VARCHAR DEFAULT 'active';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES users(id);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

-- Boards
ALTER TABLE boards ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE boards ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES users(id);
ALTER TABLE boards ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE boards ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

-- Board Columns
ALTER TABLE board_columns ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES organizations(id);
ALTER TABLE board_columns ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE board_columns ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE board_columns ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
